algoritmo "estrutura-de-repeticão-simples(tutorial)"
var
   C: inteiro
inicio
C <- 0 //Esta variavel ira receber o número 0.
enquanto (C <= 10) faca // 10 será o limete das repetições.
  escreval(C)// A variavel pegou 0 de cima, que nesse caso é 0.
C <- C + 1 // O C que esta somando com 0, e o C que esta recebendo, agora é 1.
fimenquanto // chegando aqui cera reiniciado, até que chegue ao número 10,
//ou outro número que você escreva(faça o teste!;)

fimalgoritmo